spring:
  application:
    name: reminder
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:reminder_db}
    username: ${POSTGRES_USER:reminder_user}
    password: ${POSTGRES_PASSWORD:reminder_password}
